# Generated by Django 3.0.8 on 2020-09-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200924_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewery',
            name='user',
        ),
    ]
