# Generated by Django 3.0.8 on 2020-09-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200922_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='brewery_type',
            field=models.CharField(default='micro', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewery',
            name='api_id',
            field=models.IntegerField(),
        ),
    ]
