# Generated by Django 3.0.8 on 2020-09-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200922_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_fk',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='sup', max_length=200),
            preserve_default=False,
        ),
    ]
